name: user_repository
description: Dart package which manages the user authentication stuffs.
version: 1.0.0
publish_to: none

environment: 
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  cache:
    path: ../cache
  firebase_core: ^1.7.0
  equatable: ^2.0.3
  firebase_auth: ^3.1.3
  cloud_firestore: ^3.1.8
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.1
  json_serializable: ^6.1.4
