// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMC5xaln198PvbVgse6QXSafielZtZJz4',
    appId: '1:556798406994:web:43992f4fed87e83c5aca8b',
    messagingSenderId: '556798406994',
    projectId: 'packs-app-307017',
    authDomain: 'packs-app-307017.firebaseapp.com',
    storageBucket: 'packs-app-307017.appspot.com',
    measurementId: 'G-LF8GP44GTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMC5xaln198PvbVgse6QXSafielZtZJz4',
    appId: '1:556798406994:android:b7b9add537bc51a35aca8b',
    messagingSenderId: '556798406994',
    projectId: 'packs-app-307017',
    storageBucket: 'packs-app-307017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoJaPsG9ZxEjtddvYNnI6iYGvDgOJNx2E',
    appId: '1:556798406994:ios:6e7a15e0aff986335aca8b',
    messagingSenderId: '556798406994',
    projectId: 'packs-app-307017',
    storageBucket: 'packs-app-307017.appspot.com',
    androidClientId:
        '556798406994-svv0u77lbn1ldgb9c0il34a7o6intrr5.apps.googleusercontent.com',
    iosClientId:
        '556798406994-grpdbmphfdg4nbb89irk93cnruhcgvqv.apps.googleusercontent.com',
    iosBundleId: 'com.packsinternational.packs',
  );
}
